Repository BeeBombshell/Python-DSA, pull requests merged in 2021-10, with the labels that each got.

#1 Updated README.md
  README.md
Labels: hacktoberfest

#3 Updated README.md
  README.md
Labels: hacktoberfest-accepted

#6 Added Sorting Algorithms
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added Linear Search in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#9 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 Implemented quick sort algorithm
  .gitignore
  Sorting Algorithms/quick_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#16 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#17 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 Update quick_sort.py
  Sorting Algorithms/quick_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create selection_sort.py
  Sorting Algorithms/selection_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#21 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#20 added: Binary Search
  Search Algorithms/binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted

#22 Update quick_sort.py
  Sorting Algorithms/quick_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#25 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#26 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#28 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#30 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#32 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#33 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#36 Creating heapSort.py
  Sorting Algorithms/heapSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#38 created bubble_sort.py
  Sorting Algorithms/bubble_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added bfs and dfs search algorithms
  bfs.py
  dfs.py
Labels: hacktoberfest, hacktoberfest-accepted

#39 added linear search and shell sort algorithm
  Search Algorithms/linear_search.py
  Sorting Algorithms/shell_sort.py
  Sorting Algorithms/tree_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Implemented insertion sort and bubble sort
  README.md
  Sorting Algorithms/bubble_sort.py
  Sorting Algorithms/insertion_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#45 added code for dictionary
  DSA/dictionary.py
Labels: hacktoberfest, hacktoberfest-accepted

#44 added code for tuples
  DSA/tuples.py
Labels: hacktoberfest, hacktoberfest-accepted

#43 Moved dfs and bfs into tree data structure folder
  Tree Data Structure/bfs.py
  Tree Data Structure/dfs.py
Labels: hacktoberfest, hacktoberfest-accepted

#46 created a folder named DSA and wrote code for arrays
  DSA/arrays.py
  DSA/lists.py
Labels: hacktoberfest, hacktoberfest-accepted

#41 Create radix_sort.py
  Sorting Algorithms/radix_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#47 Create bucket_sort.py
  Sorting Algorithms/bucket_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#48 wrote code for linked list
  DSA/linkedlist.py
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added Linked List program with detailed functionalities (issue resolved #42)
  DSA/LinkedList.py
Labels: hacktoberfest, hacktoberfest-accepted

#52 Added optimized function for bubble sort.
  Sorting Algorithms/bubble_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#55 Added two programs on Recursion
  README.md
  Recursion/Factorial_Recursion.py
  Recursion/Fibonacci_Series.py
Labels: hacktoberfest, hacktoberfest-accepted

#56 Added count sort
  Sorting Algorithms/countSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#58 added mergesort function
  Sorting Algorithms/mergesort.py
Labels: hacktoberfest, hacktoberfest-accepted

#62 Create Tower_of_Honai.py
  Recursion/Tower_of_Honai.py
Labels: hacktoberfest, hacktoberfest-accepted

#63 Added recursive sum
  Recursion/recursive_sum.py
Labels: hacktoberfest, hacktoberfest-accepted

#61 added Check_Bracketing & First_Non_Repeating chars DSA sols
  DSA/Check Bracketing.py
  DSA/first_non_repeating_character_of_string.py
  DSA/linkedlist.py
Labels: hacktoberfest, hacktoberfest-accepted
